service: RetoTecnico

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  obtenerPelicula:
    handler: dist/handler.obtenerPeliculaHandler
    events:
      - http:
          path: films/{id}
          method: get

  obtenerPersonaje:
    handler: dist/handler.obtenerPersonajeHandler
    events:
      - http:
          path: people/{id}
          method: get

  listarPersonajes:
    handler: dist/handler.listarPersonajesHandler
    events:
      - http:
          path: people
          method: get

  listarPeliculas:
    handler: dist/handler.listarPeliculasHandler
    events:
      - http:
          path: films
          method: get

plugins:
  - serverless-offline

